paths:
  raw: data/raw/crime.csv
  raw_dir: data/raw
  interim: data/interim/clean.csv
  processed_train: data/processed/train.csv
  processed_test: data/processed/test.csv
  artifacts_dir: models/artifacts
  model_path: models/model.pkl

data:
  target: TYPE
  drop_columns: [MINUTE, HUNDRED_BLOCK]   # noisy / high cardinality
  datetime_columns:
    year: YEAR
    month: MONTH
    day: DAY
    hour: HOUR
  cat_columns: [NEIGHBOURHOOD]
  geo_columns: [Latitude, Longitude]      # optional binning
  test_size: 0.2
  random_state: 42
  sample_frac: 1.0                        # set <1.0 to speed experiments

features:
  neighbourhood_target_encoding: true
  geo_hexbin: false
  geo_precision: 3                        # used if hexbin enabled
  scale_numeric: false

model:
  algorithm: random_forest                 # options: logistic, random_forest, xgboost
  random_forest:
    n_estimators: 250
    max_depth: 20
    n_jobs: -1
    class_weight: balanced_subsample
  logistic:
    C: 1.0
    max_iter: 200
  xgboost:
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 6
    subsample: 0.9
    colsample_bytree: 0.9
    eval_metric: mlogloss

evaluation:
  average: macro
  top_k_errors: 30
